// ABOUTME: Tests that the digests handed to privd are the lock's, not whatever
// ABOUTME: the stage directory happens to hold when the adapter reads it.

//go:build linux

package jailer

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/2389-research/observatory-v2/internal/privd"
)

// stagedFixture writes every name privd expects into a fresh stage directory and
// returns the directory. All five hold the same bytes; only the two the lock
// pins are treated differently by computeStagedFiles.
func stagedFixture(t *testing.T, content []byte) string {
	t.Helper()
	dir := t.TempDir()
	for _, name := range privd.StagedFileNames {
		if err := os.WriteFile(filepath.Join(dir, name), content, 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return dir
}

func hexSHA(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// TestComputeStagedFilesReportsThePinnedDigest is the positive control: with the
// staged copy matching the lock, every name gets a digest and nothing is refused.
func TestComputeStagedFilesReportsThePinnedDigest(t *testing.T) {
	content := []byte("the pinned artifact bytes")
	dir := stagedFixture(t, content)

	files, err := computeStagedFiles(dir, map[string]string{
		"vmlinux":     hexSHA(content),
		"rootfs.ext4": hexSHA(content),
	})
	if err != nil {
		t.Fatalf("computeStagedFiles: %v", err)
	}
	if len(files) != len(privd.StagedFileNames) {
		t.Fatalf("got %d staged files, want %d", len(files), len(privd.StagedFileNames))
	}
	for _, f := range files {
		if f.SHA256 != hexSHA(content) {
			t.Errorf("%s: digest %s, want %s", f.Name, f.SHA256, hexSHA(content))
		}
	}
}

// TestComputeStagedFilesRefusesAStagedCopyThatDriftedFromTheLock is the point of
// the cross-check. privd verifies the staged bytes against a digest this side of
// the wire computes; computing it from the staged file alone makes that check
// agree with itself no matter what is in the file. The lock is the only party
// that can disagree.
func TestComputeStagedFilesRefusesAStagedCopyThatDriftedFromTheLock(t *testing.T) {
	dir := stagedFixture(t, []byte("bytes that reached the stage directory"))
	pinned := hexSHA([]byte("bytes the lock pins"))

	files, err := computeStagedFiles(dir, map[string]string{
		"vmlinux":     pinned,
		"rootfs.ext4": pinned,
	})
	if files != nil {
		t.Error("computeStagedFiles returned a file list for a staged copy that does not match the lock")
	}
	if err == nil {
		t.Fatal("expected a refusal, got nil")
	}
	if !strings.Contains(err.Error(), "vmlinux") {
		t.Errorf("refusal should name the staged file that drifted: %v", err)
	}
	if !strings.Contains(err.Error(), pinned) {
		t.Errorf("refusal should carry the pinned digest an operator can compare: %v", err)
	}
}

// TestComputeStagedFilesAbsentFileIsNotADriftRefusal keeps the two apart, so a
// staging bug that never wrote the file cannot be read as the cross-check working.
func TestComputeStagedFilesAbsentFileIsNotADriftRefusal(t *testing.T) {
	content := []byte("the pinned artifact bytes")
	dir := stagedFixture(t, content)
	if err := os.Remove(filepath.Join(dir, "vmlinux")); err != nil {
		t.Fatalf("remove vmlinux: %v", err)
	}

	_, err := computeStagedFiles(dir, map[string]string{
		"vmlinux":     hexSHA(content),
		"rootfs.ext4": hexSHA(content),
	})
	if err == nil {
		t.Fatal("expected a refusal for the missing staged file, got nil")
	}
	if !errors.Is(err, os.ErrNotExist) {
		t.Errorf("a missing staged file must classify as absent, not as drift: %v", err)
	}
}

// TestComputeStagedFilesLeavesUnpinnedFilesAlone records the honest limit: three
// of the five staged files are generated by this adapter on this launch and the
// lock says nothing about them, so their digests are self-reported and privd's
// check of them proves only that the copy into the jail was faithful.
func TestComputeStagedFilesLeavesUnpinnedFilesAlone(t *testing.T) {
	content := []byte("generated for this boot")
	dir := stagedFixture(t, content)

	files, err := computeStagedFiles(dir, map[string]string{})
	if err != nil {
		t.Fatalf("computeStagedFiles with nothing pinned: %v", err)
	}
	if len(files) != len(privd.StagedFileNames) {
		t.Fatalf("got %d staged files, want %d", len(files), len(privd.StagedFileNames))
	}
}
